### PR TITLE
doc: add a link to https://www.openvswitch.org

### PR DESCRIPTION
**Pull request by goneri**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/456
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/458
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/459
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/463

### CODE REVIEW

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by danielmellado** [comment]
Please rebase this against the current README ;)

**Pull request closed without merging**
